language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update && sudo apt-get install -y cmake libgtest-dev llvm-3.4 llvm-3.4-dev

script: mkdir build && cd build && cmake .. && make && ./test
